### ISSUE TITLE
Varagin on bypassdlgradient

### ISSUE THREAD

**Issue by kevinherisse** [matlab-deep-learning/quantization-aware-training#1]
Hello,
When I'm using bypassdlgradients with @ round and varargin such as "TieBreaker", the error "Too many input arguments" appears. The comments indicate that it is possible to add additional arguments to the function, is this already implemented?
Thank you for your work, it's amazing !!

**Comment by dorrubin** [comment]
Hi Kevin,

There is a small typo in the help text. You can add arguments to `round` by defining the function handle as shown below. 

```
fcn = @(x) round(x, 'TieBreaker', 'odd');
bypassdlgradients(fcn, dlarray(3.5));
```

I have updated the help text.  Glad you find the example useful!

**Comment by kevinherisse** [comment]
Hi, thank you Dor for the help.
I just tried and it seems that there is an error with the STE.

Error using [DAGNetwork/classify](matlab:matlab.internal.language.introspective.errorDocCallback('DAGNetwork/classify'))
Error using the predict function in layer quantizationLayer. The function threw an error and could not be
executed.

Caused by:
    Error using [gpuArray/round](matlab:matlab.internal.language.introspective.errorDocCallback('gpuArray/round'))
    Too many input arguments.

    Error in [WeightQuantization>@(x)round(x,'TieBreaker','odd')](matlab:matlab.internal.language.introspective.errorDocCallback('WeightQuantization>@(x)round(x,''TieBreaker'',''odd'')',...
        fcn = @(x) round(x,'TieBreaker','odd');

    Error in CustomStraightThroughEstimator/forward

    Error in [deep.internal.dlarray.extension.applyForward](matlab:matlab.internal.language.introspective.errorDocCallback('deep.internal.dlarray.extension.applyForward',...
        [varargout{1:nargout}] = forward(meth, varargin{:});

    Error in [deep.internal.dlarray.extension.applyExtensionMethod](matlab:matlab.internal.language.introspective.errorDocCallback('deep.internal.dlarray.extension.applyExtensionMethod', 'C:\Program Files\MATLAB\R2022b\toolbox\nnet\deep\+deep\+internal\+dlarray\+extension\applyExtensionMethod.m', 30)) ([line 30](matlab: opentoline('C:\Program Files\MATLAB\R2022b\toolbox\nnet\deep\+deep\+internal\+dlarray\+extension\applyExtensionMethod.m',30,0)))
    [numericData{1:numOutputs}] = deep.internal.dlarray.extension.applyForward(meth, numericData{:});

    Error in [bypassdlgradients](matlab:matlab.internal.language.introspective.errorDocCallback('bypassdlgradients'))

**Comment by dorrubin** [comment]
Didn't realize you were using a `gpuArray` unfortunately, `gpuArray` doesn't support `round` with additional arguments.

```
>> round(gpuArray(3.5), "TieBreaker", "odd")
Error using round
Too many input arguments.
```

I have created an enhancement request to add support for TieBreaker options on GPU. To help with the request, can you add some background for why you specifically want to use non-default rounding with quantization aware training?

**Comment by kevinherisse** [comment]
I'm training a neural network that will be implemented on an ASIC with a specific method for MAC operation. The way we do the computation makes the final result rounded toward zero. I wanted to add this to my training to help improve the accuracy.

Thanks for your help.
